spring:
  application:
    name: jrtpminiproject2

  mail:
    host: smtp.gmail.com
    port: 587
    username: addankilingababu@gmail.com
    password: your_gmail_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/usermanagementdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
