spring:
  application:
    name: product_api
  datasource:
    url: jdbc:mysql://localhost:3306/jrtpmajorprojectdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true