spring:
  application:
    name: product_api

  datasource:
    url: jdbc:mysql://localhost:3306/e_commdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8081
